### ISSUE TITLE
请问怎么将JWT密码设置成可配置的呢？

### ISSUE THREAD

**Issue by WuJonah** [freew01f/securing-spring-boot-with-jwts#6]
static final String SECRET = "P@ssw02d";         // JWT密码
这里改怎么改成可配置的密码。？
我用注解@Value注入报错。是不是 static final需要另外的注入方式，？麻烦博主能帮忙看下。

**Comment by freew01f** [comment]
static final 是没法注入的 你换成 private final String SECRET 就可以了 
你去看看啥叫static 和 ioc的基本概念就知道了
